export enum ModalTypes{
    YES_NO_DIALOG = "YES_NO_DIALOG",
    CREATE_EDIT_ARTICLE_MODAL = "CREATE_EDIT_ARTICLE_MODAL",
    CREATE_EDIT_NOTE_MODAL = "CREATE_EDIT_NOTE_MODAL",
    CREATE_EDIT_PROJECT_MODAL = "CREATE_EDIT_PROJECT_MODAL",
    CREATE_EDIT_TAG_MODAL = "CREATE_EDIT_TAG_MODAL",
}